
int BUZZER_PIN = 12;
int BUZZER_CHANNEL = 0;
int NO_SOUND = 0;

void setup() {

  ledcAttachPin(BUZZER_PIN, BUZZER_CHANNEL);
}
void loop() {

ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(900.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(900.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(900.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(900.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(225.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(450.0);
ledcWriteNote(BUZZER_CHANNEL, (note_t)NOTE_B, 5);
delay(900.0);
  }


     
